# Generated by Django 5.0 on 2023-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://static.wixstatic.com/media/bf242e_6133b4ae6a104cc2b50d70179f35efea~mv2.jpg/v1/fill/w_500,h_376,al_c,lg_1,q_80,enc_auto/food-placeholder.jpg",
                max_length=500,
            ),
        ),
    ]
